In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)
print("Shape:", arr1.shape)
print("Data Type:", arr1.dtype)

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n2D Array:\n", arr2)
print("Shape:", arr2.shape)
print("Data Type:", arr2.dtype)




1D Array: [10 20 30 40 50]
Shape: (5,)
Data Type: int64

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data Type: int64


In [ ]:
zeros1D = np.zeros(8)
print("1D Array of Zeros:", zeros1D)

ones2D = np.ones((4,4))
print("\n2D Array of Ones:\n", ones2D)

zeros2D = np.zeros((3,3))
print("\n3x3 Matrix of Zeros:\n", zeros2D)


1D Array of Zeros: [0. 0. 0. 0. 0. 0. 0. 0.]

2D Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 Matrix of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:

print("Numbers from 0 to 20:", np.arange(0,21,1))
print("Even numbers from 10 to 50:", np.arange(10,51,2))
print("Numbers from 5 to 100 step 5:", np.arange(5,101,5))


Numbers from 0 to 20: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even numbers from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
Numbers from 5 to 100 step 5: [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [ ]:
arr1 = np.linspace(0,5,10)
print("10 equally spaced numbers between 0 and 5:", arr1)
print("Length:", len(arr1))

arr2 = np.linspace(-10,10,15)
print("\n15 equally spaced numbers between -10 and 10:", arr2)
print("Length:", len(arr2))


10 equally spaced numbers between 0 and 5: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10

15 equally spaced numbers between -10 and 10: [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


In [ ]:
print("1D Random Array:", np.random.rand(10))
print("\n3x3 Random Normal Matrix:\n", np.random.randn(3,3))
print("\n4x5 Random Integers:\n", np.random.randint(10,50,(4,5)))


1D Random Array: [0.5120551  0.02491237 0.97435545 0.04293673 0.12711677 0.86802566
 0.25751226 0.80925399 0.99326244 0.08012767]

3x3 Random Normal Matrix:
 [[ 1.91846693 -0.07907    -2.15892415]
 [ 0.64593951 -0.30819199  0.01020938]
 [ 0.83115622  0.47019939 -0.13744565]]

4x5 Random Integers:
 [[45 25 11 38 39]
 [21 10 12 13 41]
 [24 17 20 48 18]
 [24 25 19 12 39]]


In [ ]:
v1 = np.array([2,4,6,8])
v2 = np.array([1,3,5,7])

print("Addition:", v1+v2)
print("Subtraction:", v1-v2)
print("Element-wise Multiplication:", v1*v2)
print("Dot Product:", np.dot(v1,v2))


Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Element-wise Multiplication: [ 2 12 30 56]
Dot Product: 100


In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("Matrix Addition:\n", A+B)
print("\nMatrix Multiplication:\n", A@B)
print("\nElement-wise Multiplication:\n", A*B)


Matrix Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [ ]:
arr = np.random.randint(1,100,(4,4))
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Minimum Value:", arr.min())
print("Maximum Value:", arr.max())


Array:
 [[26 43 42 84]
 [59 74 17 49]
 [99 94 98  5]
 [54 40 93 81]]
Shape: (4, 4)
Dimension: 2
Size: 16
Data Type: int64
Minimum Value: 5
Maximum Value: 99


In [ ]:
arr = np.random.randint(1,50,20)
print("1D Array:", arr)

matrix = arr.reshape(4,5)
print("\nReshaped 4x5 Matrix:\n", matrix)

print("\nSum:", matrix.sum())
print("Mean:", matrix.mean())
print("Standard Deviation:", matrix.std())
print("\nMax in each row:", matrix.max(axis=1))


1D Array: [26 24 29 20 13 18 23 30 32 28 18 33 49 25 42 18  7 19 49 38]

Reshaped 4x5 Matrix:
 [[26 24 29 20 13]
 [18 23 30 32 28]
 [18 33 49 25 42]
 [18  7 19 49 38]]

Sum: 541
Mean: 27.05
Standard Deviation: 10.887952057205249

Max in each row: [29 32 49 49]


In [ ]:
try:
    n = int(input("Enter how many numbers to generate: "))
    arr = np.random.randint(10,100,n)
    print("\nGenerated Array:", arr)
    print("Mean:", np.mean(arr))
    print("Median:", np.median(arr))
    print("Standard Deviation:", np.std(arr))
    print("Minimum:", np.min(arr))
    print("Maximum:", np.max(arr))

    if n % 2 == 0:
        matrix = arr.reshape(2, n//2)
        print("\nReshaped 2D Array:\n", matrix)
        print("Row-wise Sum:", matrix.sum(axis=1))
    else:
        print("\nCannot reshape into 2D array (odd number of elements).")
except Exception as e:
    print("Error:", e)


Enter how many numbers to generate: 6

Generated Array: [82 74 96 35 15 55]
Mean: 59.5
Median: 64.5
Standard Deviation: 27.83732506306356
Minimum: 15
Maximum: 96

Reshaped 2D Array:
 [[82 74 96]
 [35 15 55]]
Row-wise Sum: [252 105]


In [ ]:
!git clone https://github.com/bodkhesakshi03-dotcom/AIML_Assignment_Session13.git


Cloning into 'AIML_Assignment_Session13'...


In [ ]:
!git clone https://github.com/bodkhesakshi03-dotcom/AIML_Assignment_Session13.git
%cd AIML_Assignment_Session13



fatal: destination path 'AIML_Assignment_Session13' already exists and is not an empty directory.
/content/AIML_Assignment_Session13


In [6]:
from google.colab import drive
drive.mount('/content/drive')





Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
!ls /content/drive/MyDrive


'Colab Notebooks'


In [8]:
!ls "/content/drive/MyDrive/Colab Notebooks"


 13.ipynb	     student_management.py   Untitled0.ipynb
'Copy of 13.ipynb'   Untitled


In [12]:
%cd AIML_Assignment_Session13



[Errno 2] No such file or directory: 'AIML_Assignment_Session13'
/content


In [14]:
!cp "/content/drive/MyDrive/Colab Notebooks/13.ipynb" .


In [15]:
!git config --global user.email "bodkhesakshi03@gmail.com"

In [16]:
!git config --global user.name "sakshi bodkhe"

In [17]:
!git add 13.ipynb

fatal: not a git repository (or any of the parent directories): .git


In [18]:
!git commit -m "Added assignment notebook"

fatal: not a git repository (or any of the parent directories): .git


In [19]:
!git push origin main

fatal: not a git repository (or any of the parent directories): .git


In [20]:
!git clone https://github.com/bodkhesakshi03-dotcom/AIML_Assignment_Session13.git


Cloning into 'AIML_Assignment_Session13'...
