In [1]:
import numpy as np

arr = np.random.randint(10, 101, size=(5, 6))
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)


Array:
 [[ 26 100  20  83  47  49]
 [ 46  65  71  48  41  98]
 [ 58  89  72  27  55  32]
 [ 91  43  20  81  34  22]
 [ 58  25  51  63  81  59]]
Shape: (5, 6)
Size: 30
Data type: int64


In [2]:
arr = np.random.randint(1, 51, size=20)
print("Array:", arr)
print("Min value:", arr.min(), "at index", arr.argmin())
print("Max value:", arr.max(), "at index", arr.argmax())
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())


Array: [17 17 22 10 37 41 21 17 31 10 43 34  6 25 41 49 23 39  7 47]
Min value: 6 at index 12
Max value: 49 at index 15
Sum: 537
Mean: 26.85
Standard Deviation: 13.491756742544688


In [3]:
arr = np.random.randint(20, 81, size=(4, 5))
print("Matrix:\n", arr)
print("Min:", arr.min())
print("Max:", arr.max())
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Std Dev:", arr.std())
print("Row sums:", arr.sum(axis=1))
print("Column sums:", arr.sum(axis=0))


Matrix:
 [[49 22 68 65 41]
 [41 63 61 46 67]
 [43 75 80 76 22]
 [39 21 23 67 76]]
Min: 21
Max: 80
Sum: 1045
Mean: 52.25
Std Dev: 19.595598995692885
Row sums: [245 278 296 226]
Column sums: [172 181 232 254 206]


In [4]:
arr = np.arange(1, 25)
print("Reshape (4,6):\n", arr.reshape(4, 6))
print("Reshape (3,8):\n", arr.reshape(3, 8))
print("Reshape (2,3,4):\n", arr.reshape(2, 3, 4))


Reshape (4,6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Reshape (3,8):
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Reshape (2,3,4):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [5]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print("First row:", arr[0])
print("Last column:", arr[:, -1])
print("Center 2x2 submatrix:\n", arr[1:3, 1:3])
print("Even numbers:", arr[arr % 2 == 0])


First row: [10 20 30 40]
Last column: [ 40  80 120]
Center 2x2 submatrix:
 [[ 60  70]
 [100 110]]
Even numbers: [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [6]:
arr = np.random.randint(1, 101, size=(5, 5))
print("Matrix:\n", arr)
print("Diagonal:", np.diag(arr))
print("Greater than 50:", arr[arr > 50])
arr[arr < 30] = 0
print("Modified Matrix:\n", arr)


Matrix:
 [[ 42  19  31  51  40]
 [ 35  62  12  23   4]
 [ 25  80  52 100 100]
 [ 36  48   3  10  78]
 [ 23  72   4  86  38]]
Diagonal: [42 62 52 10 38]
Greater than 50: [ 51  62  80  52 100 100  78  72  86]
Modified Matrix:
 [[ 42   0  31  51  40]
 [ 35  62   0   0   0]
 [  0  80  52 100 100]
 [ 36  48   0   0  78]
 [  0  72   0  86  38]]


In [7]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** b)
print("Modulo:", a % b)


Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Power: [     10     400   27000 2560000]
Modulo: [0 0 0 0]


In [8]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("Element-wise multiplication:\n", A * B)
print("Matrix multiplication:\n", A @ B)

# Comment: (*) multiplies element by element, while (@) performs matrix multiplication (dot product).


Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [9]:
arr = np.random.randn(6, 6)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Index of maximum:", arr.argmax())
print("Index of minimum:", arr.argmin())
print("Top-left 3x3 submatrix:\n", arr[:3, :3])
arr[arr < 0] = np.abs(arr[arr < 0])
print("Modified array:\n", arr)
print("Mean of modified array:", arr.mean())


Shape: (6, 6)
Size: 36
Data type: float64
Index of maximum: 1
Index of minimum: 25
Top-left 3x3 submatrix:
 [[ 1.25694399  1.86950058 -0.80118524]
 [ 1.44900673 -0.88815455  0.08820601]
 [ 0.86193741  0.29823884 -0.82586882]]
Modified array:
 [[1.25694399 1.86950058 0.80118524 1.15605426 0.77951817 1.88409447]
 [1.44900673 0.88815455 0.08820601 0.52197433 0.7103034  1.06054844]
 [0.86193741 0.29823884 0.82586882 1.13342915 0.06192498 1.02243155]
 [0.79311535 1.36988202 0.1898248  0.67292244 0.58499006 0.40884673]
 [1.15717817 2.00088653 1.80989021 0.28501438 1.59867604 0.8632533 ]
 [0.51919477 1.00704222 0.01470609 0.17811575 0.37067433 0.57224389]]
Mean of modified array: 0.8629382784265729


In [10]:
import numpy as np

# Generate a 2D array of shape (10 students × 5 subjects) with random marks between 30 and 100
marks = np.random.randint(30, 101, size=(10, 5))
print("Marks Array:\n", marks)

# For each student, calculate total marks and average
totals = marks.sum(axis=1)
averages = marks.mean(axis=1)
print("Total marks per student:", totals)
print("Average marks per student:", averages)

# Find the student with highest and lowest total marks (using argmax/argmin)
print("Highest total by Student:", totals.argmax(), "with", totals.max())
print("Lowest total by Student:", totals.argmin(), "with", totals.min())

# Calculate overall class mean and standard deviation
print("Class Mean:", marks.mean())
print("Class Std Dev:", marks.std())

# Demonstrate indexing: extract marks of top 3 students
top3_indices = totals.argsort()[-3:][::-1]   # indices of top 3 students
print("Marks of Top 3 Students:\n", marks[top3_indices])

# Comment: Each step shows array operations, indexing, and statistical analysis as required.


Marks Array:
 [[ 87  71  85  81  56]
 [ 92  71  50  33  47]
 [ 39  62  77  30  55]
 [ 64  68  35  73  63]
 [100  54  58  32  85]
 [ 77  55  65  38  61]
 [ 56  41  42  41  95]
 [ 33  54  63  98  92]
 [ 92  51  49  41  91]
 [ 71  47  54  73  63]]
Total marks per student: [380 293 263 303 329 296 275 340 324 308]
Average marks per student: [76.  58.6 52.6 60.6 65.8 59.2 55.  68.  64.8 61.6]
Highest total by Student: 0 with 380
Lowest total by Student: 2 with 263
Class Mean: 62.22
Class Std Dev: 19.403391456134674
Marks of Top 3 Students:
 [[ 87  71  85  81  56]
 [ 33  54  63  98  92]
 [100  54  58  32  85]]


In [11]:
!git config --global user.email "bodkhesakshi03@gmail.com"

In [12]:
!git clone https://github.com/bodkhesakshi03-dotcom/AIML_Assignment_Session14.git

Cloning into 'AIML_Assignment_Session14'...


In [13]:
!cp /content/14.ipynb AIML_Assignment_Session14/


cp: cannot stat '/content/14.ipynb': No such file or directory
